server:
  port: 8080
  servlet:
    context-path: /dev-api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lucky_admin_vue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mysql
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      password:
# 项目设置
lucky:
  # 验证码开关
  captcha-enabled: true
  # 验证码类型 number-数字 text-字符 mixed-数字+字母 math-计算
  captcha-type: number
  # IP取位置是否开启
  ip-location: true
  # 文件上传路径
  profile: D:/lucky-admin-vue-file/file/
